€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 37, in get_classes
    choices =['Name: {}, Students: {}/8, Time: {}, '.format(
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 41, in <listcomp>
    ) + 'Days: {}'.format(d.name) for d in days if d.lessons == i.id
UnboundLocalError: local variable 'i' referenced before assignment
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 37, in get_classes
    choices =['Name: {}, Students: {}/8, Time: {}, '.format(
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 41, in <listcomp>
    ) + 'Days: {}'.format(d.name) for d in days if d.lessons == i.id
UnboundLocalError: local variable 'i' referenced before assignment
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 37, in get_classes
    choices =['Name: {}, Students: {}/8, Time: {}, Days:'.format(
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 37, in <listcomp>
    choices =['Name: {}, Students: {}/8, Time: {}, Days:'.format(
TypeError: can only concatenate str (not "generator") to str
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 37, in get_classes
    choices =['Name: {}, Students: {}/8, Time: {}, Days:'.format(
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 37, in <listcomp>
    choices =['Name: {}, Students: {}/8, Time: {}, Days:'.format(
TypeError: can only concatenate str (not "generator") to str
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 46, in get_classes
    choice = 'Name: {}, Students: {}/8, Time: {}, Days: '.format(
TypeError: can only concatenate str (not "generator") to str
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
